### ISSUE TITLE
Inlining JSON in to index.html

### ISSUE THREAD

**Issue by felixakiragreen** [okonet/webpack-long-term-cache-demo#1]
In your [article](https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95) you say: `This is easy as inlining the contents of the JSON in HTML. Our HTML head section should look like this:`

I've spend several hours trying to figure this out and I'm still struggling. In this example http://clarkdave.net/2015/01/how-to-use-webpack-with-rails/#including-precompiled-assets-in-views ruby is used but I want to do it just with webpack.

Any help?

**Comment by okonet** [comment]
If you want to use static HTML, there is a static-site-generator-webpack-plugin for webpack: https://github.com/markdalgleish/static-site-generator-webpack-plugin

Or take a look at something like http://www.metalsmith.io/ or http://wintersmith.io/ or even grunt/gulp task.

**Comment by felixakiragreen** [comment]
Thanks. I found this which is working for me: https://github.com/ampedandwired/html-webpack-plugin
