### ISSUE TITLE
it seems didn't work

### ISSUE THREAD

**Issue by geraldlrh** [okonet/webpack-long-term-cache-demo#2]
![image](https://cloud.githubusercontent.com/assets/1524717/11019296/09641d48-862e-11e5-8adf-b5dbb25a84f9.png)
between two builds I change the moduleB.js，but the hash of vendor changed.

**Comment by dennis-johnson-dev** [comment]
@geraldlrh I ran into the same thing, this appears to be a bug in webpack - https://github.com/webpack/webpack/issues/1315

**Comment by geraldlrh** [comment]
@songawee got it, thanks

**Comment by ericlau-solid** [comment]
I am getting the same issue as well. Nothing I can about it it seems until webpack has a fix.

**Comment by bardt** [comment]
I've just created pull request https://github.com/okonet/webpack-long-term-cache-demo/pull/3 with a fix for webpack hashing mechanics.
