### ISSUE TITLE
Is WebpackMd5Hash necessary?

### ISSUE THREAD

**Issue by coryhouse** [okonet/webpack-long-term-cache-demo#5]
Thanks so much for the awesome blog post! 

WebpackMd5Hash isn't mentioned in the blog post. Why is it necessary?

https://github.com/okonet/webpack-long-term-cache-demo/blob/master/webpack.config.js#L22

**Comment by coryhouse** [comment]
After testing, I can see that WebpackMd5Hash is required. Otherwise, a different filename is generated on every build. However, based on the docs, WebpackMd5Hash simply tells webpack to use MD5 instead of its standard webpack chunkhash. Apparently its standard chunkhash isn't deterministic, which is why WebpackMd5Hash is useful. Thanks again for the great post and example!

**Comment by coryhouse** [comment]
One suggestion: WebpackMd5Hash isn't mentioned in the blog post. I assume that's an accidental omission.

**Comment by demondiff** [comment]
Hi , this post https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31 mentions using NamedModulesPlugin and NamedChunksPlugin for reasons mentioned in the blog. Are all these problems fixed if I use WebpackMd5Hash instead. ?
